spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:products-db
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ama-realm
          jwk-set-uri: http://localhost:8080/realms/ama-realm/protocol/openid-connect/certs
server:
  port: 8090